# Change these first
owner: appellet # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Git
    url: https://git.tibiscuit.ch/
  - name: Plex
    url: https://plex.tibiscuit.ch/web/index.html
  - name: TimeTagger
    url: https://tagger.tibiscuit.ch/
  #- name: Sonar
  #  url: sonar.tibiscuit.ch
  #- name: Radarr
  #  url: https://radarr.tibiscuit.ch
  #- name: Jackett
  #  url: jackett.tibiscuit.ch
  - name: QBTorrent
    url: https://qbt.tibiscuit.ch/
  - name: Joplin
    url: https://joplin.tibiscuit.ch
  #- name: Netdata
  #  url: https://netdata.tibiscuit.ch
  #- name: OwnCloud
  #  url: https://cloud.tibiscuit.ch
  #- name: Immich
  #  url: https://img.tibiscuit.ch
  # name: Netdata
  #  url: netdata.tibiscuit.ch
  #- name: Minecraft 
  #  url: mc.tibiscuit.ch
  #  port: 25565
  #  check: "tcp-ping"
  - name: Minecraft Cousins
    url: cousins.tibiscuit.ch
    port: 57429
    check: "tcp-ping"
    delay: 2000
    ipv6: true
  #- name: Minecraft Raspberry
  #  url: mc.tibiscuit.ch
  #  port: 25565
  #  check: "tcp-ping"
  #  delay: 2000
  - name: Server
    url: 45.155.170.218
    port: 2542
    check: "tcp-ping"
    delay: 2000
  - name: Raspberry Pi5
    url: 45.155.170.218
    port: 2222
    check: "tcp-ping"
    delay: 2000
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tibiscuit.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Status** of Tibiscuit's server"
  introMessage: This is a sample status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/appellet/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
